apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jg6mzoge7-go 
  janus-idp.io/tekton: jg6mzoge7-go
  backstage.io/kubernetes-id: jg6mzoge7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jg6mzoge7-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml